stages:
  - build
  - deploy
  - infrastructure

variables:
  PROJECT_ID: "reference-node-434715-i6"
  REGION: "us-central1"
  IMAGE_NAME: "my-app"

build_image:
  stage: build
  script:
    - docker build -t gcr.io/$PROJECT_ID/$IMAGE_NAME:latest .
    - docker push gcr.io/$PROJECT_ID/$IMAGE_NAME:latest
  tags:
    - docker

deploy_infrastructure:
  stage: infrastructure
  script:
    - terraform init
    - terraform apply -auto-approve
  tags:
    - terraform

deploy_app:
  stage: deploy
  script:
    - kubectl apply -f k8s/deployment.yaml
  tags:
    - kubernetes
